### ISSUE TITLE
Support passing complex config to actions

### ISSUE THREAD

**Issue by inglesp** [opensafely-core/job-runner#225]
Extracted from #124.

If a project.yaml contains

```
actions:
    myaction:
         run: action:latest file1.csv file2.csv
         config:
              foo: bar
```

then the docker command will be

```
docker run ... ghcr.io/opensafely-core/action:latest file1.csv file2.csv --config '{"foo": "bar"}'
```
