### ISSUE TITLE
Implement remote reusable actions

### ISSUE THREAD

**Issue by iaindillingham** [opensafely-core/job-runner#227]
What are *reusable* actions? Actions that can be used in more than one study, but that are not base actions. What are *base* actions? Actions that are released as images, such as `cohortextractor`.

What's required to implement reusable actions? Given the following extract from a study's *project.yaml*...

```yaml
actions:

  my_deciles_chart_action:
    run: deciles-chart-action:v0.1.0 --output-format=VL
    outputs:
      highly_sensitive:
        output: output/deciles_chart.vl.json
```

...job-runner should...

* clone `opensafely-actions/deciles-chart-action` and checkout the commit tagged `v0.1.0`.
* read *action.yaml*, identifying the runtime image and the entry point.
* build a runtime container from the runtime image and the cloned/checked out action.
* call the entry point on the runtime container, passing any configuration.

For background information, see opensafely-core/actions-registry#7.
