### ISSUE TITLE
Incorrect action syntax leads to an internal error

### ISSUE THREAD

**Issue by evansd** [opensafely-core/job-runner#728]
The specific actions in question are from [here](https://github.com/opensafely/prophy_effects_Sotro_Molnup/blob/9a5d4b621146f87248954dba9751e53e992d2f4a/project.yaml):
```yaml
  prep_descrip_r:
    run: r:analysis/data_prep_descrip.R
    ...

  prep_descrip_stata:
   run: stata-mp:analysis/data_prep_descrip.do
   ...
```

Which resulted in an internal error here:
https://jobs.opensafely.org/coverage-effectiveness-and-safety-of-neutralising-monoclonal-antibodies-or-antivirals-for-non-hospitalised-patients-with-covid-19/prophy_effects_sotro_molnup/22898/kayp43s3icchwl3q/

With the relevant traceback being:
![image](https://github.com/opensafely-core/job-runner/assets/19630/ec2bba85-744c-4365-8675-8976637747a2)

I guess we need to be stricter about validating tags when validating the project.yaml so that `analysis/data_prep_descrip.R` is no longer accepted as a valid docker image version.

Slack thread:
https://bennettoxford.slack.com/archives/C01D7H9LYKB/p1714559913897309
